### ISSUE TITLE
Xcode build error after updating to 3.2.1 from 3.1.1

### ISSUE THREAD

**Issue by grit96** [MinaSamir11/react-native-in-app-review#56]
```
$ xcodebuild -version
Xcode 12.0
Build version 12A7209
```

After updating the module from 3.1.1 to 3.2.2, I'm now getting the following Xcode build failure. The same happens on another machine with Xcode 12.2.

```
Undefined symbols for architecture arm64:

  "_swift_getFunctionReplacement", referenced from:

      _swift_getFunctionReplacement50 in libswiftCompatibilityDynamicReplacements.a(DynamicReplaceable.cpp.o)

     (maybe you meant: _swift_getFunctionReplacement50)

  "_swift_getOrigOfReplaceable", referenced from:

      _swift_getOrigOfReplaceable50 in libswiftCompatibilityDynamicReplacements.a(DynamicReplaceable.cpp.o)

     (maybe you meant: _swift_getOrigOfReplaceable50)

ld: symbol(s) not found for architecture arm64

clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by grit96** [comment]
Turns out this was because I didn't have my RN project correctly set up for Swift - https://github.com/react-native-community/upgrade-support/issues/25

**Comment by MinaSamir11** [comment]
@grit96  
Try these: https://github.com/MinaSamir11/react-native-in-app-review/issues/58#issuecomment-867328858
